---
title: "nf-core/createtaxdb data retrieval preparation for clinical metagenomics case study"
author: "Sofia Stamouli"
format: html
---

## Introduction

This notebook describes how the genomes for testing nf-core/createtaxdb in the clinical metagenomics case study were
selected.The genomes used for presenting the application of nf-core/taxprofiler in the clinical metagenomics case study were retrieved from https://benlangmead.github.io/aws-indexes/k2 using PlusPF (2/26/2026). The genomes were used to build Centrifuge and DIAMOND databases with nf-core/createtaxdb. To ensure consistency in the analysis,we also built a Kraken2 database using nf-core/createtaxdb, even though a prebuilt database is available from the same source.

The clinical samples were further analysed with nf-core/taxprofiler.

## Data retrieval

Download the list of genomes necessary to build the databases for the clinical metagenomics case study:

```{bash}
wget https://genome-idx.s3.amazonaws.com/kraken/pluspf_20260226/library_report.tsv
```

The format of this file is as follows:

| Library  | Sequence Name                                                                 | URL                                                                                           |
|----------|-------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| plasmid  | NZ_CM002625.1 Xanthomonas campestris pv. campestris str. CFBP 12824 plasmid unnamed3, whole genome shotgun sequence | genomes/refseq/plasmid/plasmid.5.1.genomic.fna.gz |
| bacteria | NZ_CABWXX010000283.1 Salmonella enterica subsp. enterica serovar Derby isolate ER1175, whole genome shotgun sequence | https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/902/509/465/GCF_902509465.1_assembly/GCF_902509465.1_assembly_genomic.fna.gz |
