---
title: "Benchmarking nf-core/createtaxdb auxiliary files retrieval"
author: "James Fellows Yates"
format: html
---

## Introduction

In addition to the reference genome files themselves, most classifier database building tools require auxiliary taxonomy metadata files.

Not all classifiers use the same taxonomy files.
Therefore we will need to download and prepare a range of files for the building itself.

More information about what is contained by these files can be found on the [nf-core/createtaxdb FAQ](https://nf-co.re/createtaxdb/2.1.0/docs/usage/usage/faq/).

## Requirements

Command line tools used in this notebook includes:

- `curl` (v8.5.0 (x86_64-pc-linux-gnu))
- `gunzip` (gunzip (gzip) 1.10)
- `tar` (tar (GNU tar) 1.34)
- `awk` (GNU Awk 4.2.1, API: 2.0)
- `taxonkit` (v0.2.0)
- `csvtk` (v0.37.0)

## Download and prepare files

### NCBI taxdump files

The most common set of auxiliary taxonomy metadata files used by the tools are from the NCBI servers:

- `names.dmp` from [`pub/taxonomy`](https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/)
- `nodes.dmp` from  from [`pub/taxonomy`](https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/)
- `nucl_gb.accession2taxid.gz` from [`pub/taxonomy/accession2taxid`](https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/)

While not used directly, we will also need to download the following, to make a variant of this file for DIAMOND.

- `prot.accession2taxid.gz` from [`pub/taxonomy/accession2taxid`](https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/)

We can download (2026-03-17) these with:

```{bash}
#| eval: false
mkdir auxiliary_files/

## For nodes and names dmp files
curl -o auxiliary_files/taxdump.tar.gz https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz

## for accession2taxid files
curl -o auxiliary_files/nucl_gb.accession2taxid.gz https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz
curl -o auxiliary_files/prot.accession2taxid.gz https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz
 
gunzip *
tar xvf auxiliary_files/taxdump.tar
rm auxiliary_files/taxdmp.tar
```

### NCBI genome.sizes

We can download the NCBI genome-sizes file:

```{bash}
#| eval: false
curl -o auxiliary_files/species_genome_size.txt https://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/species_genome_size.txt
gzip species_genome_size.txt
```

### Create nucl2taxid

To create a Kraken2 and co like `nucl2taxid` file, you can use the following `awk` command.

```{bash}
#| eval: false
awk -v OFS='\t' 'NR>1 {print $2, $3}' auxiliary_files/nucl_gb.accession2taxid > auxiliary_files/nucl2taxid.map
```

### Create prot2taxid

To create a DIAMOND compatible `prot2taxid` file, you can use a similar `awk` command above, just retaining the header.

```{bash}
#| eval: false
awk -v OFS='\t' '{print $2, $3}' auxiliary_files/prot.accession2taxid > auxiliary_files/prot2taxid.map
```

### Download MALT db

To get the MALT taxonomy mappings, we download from the MEGAN website, and unzip.

```{bash}
#| eval: false
curl -o auxiliary_files/megan-nucl-Feb2022.db.zip https://software-ab.cs.uni-tuebingen.de/download/megan6/megan-nucl-Feb2022.db.zip
```

::: {.callout-warning}
At time of analysis, website was unavailable, so not included in analyses!
:::

### Sylph Taxonomy

Sylph requires a custom taxonomy file that does not follow a typical NCBI `taxdmp` structure.

:::{.callout-note}
This is taxonomy file is currently supplied to nf-core/taxprofiler rather than nf-core/createtaxdb, as the file is used in a post-profiling conversion step.
:::

Instead, the`sylph` assigns to each _filename_ a character-based taxonomy string. 
We will then need to generate this manually for nf-core/taxprofiler.

Fortunately a combination of `taxonkit` provides similar functionality for us to generate this from our existing samplesheet (see createtaxdb-data-retrieval-preparation.qmd) and NCBI taxonomy files we downloaded above.

From within the benchmarking directory we can run:

```{bash}
cat samplesheets/createtaxdb-samplesheet_raven.csv | \
  csvtk csv2tab | \
  taxonkit --data-dir auxiliary_files/ reformat2 -I 2 -f "k__{domain|acellular root|superkingdom};p__{phylum};c__{class};o__{order};f__{family};g__{genus};s__{species}" | \
  cut -f 2,5 | \
  sed '1d;' > auxiliary-files/sylph_taxonomy.tsv
```

:::{.callout-note}
Note that sylph-tax >= v1.7 uses a full file name instead of the first half of NCBI accessions.
nf-core/taxprofiler currently only includes a pre-v1.7 version thus just uses the `GCF_` code.
:::
