---
title: "Benchmarking nf-core/taxprofiler pipeline execution"
author: "James Fellows Yates"
format: html
---

## Introduction

The notebook describes the set up of the execution of the nf-core/taxprofiler benchmarking run.

## Requirements

Command line tools used in this notebook includes:

  - `nextflow` (version 25.10.4 build 11173)

## Retrieving pipeline

We will benchmarking with v2.1.0 of nf-core/taxprofiler with Nextflow version 25.10.4.

```{bash}
#| eval: false
nextflow pull nf-core/taxprofiler -r 2.0.0
```

## Pipeline execution

Make a fresh screen session for safety

```{bash}
#| eval: false
screen -R txp
```

### Configuration files

The final config files used were as follows.

#### Raven

For large databases `custom.config`:

```{groovy}
process {
	withName: 'FASTP_PAIRED' {
		cpus   = 24
		memory = '110.GB'
	}
	withName: 'PORECHOP_ABI' {
		cpus = 72
		memory = '240.GB'
	}
	withName: 'NANOQ' {
		cpus = 24
		memory = '110.GB'
	}
	withName: 'NONPAREIL_NONPAREIL' {
		ext.args = "-k 15"
	} 
        withName: 'KAIJU_KAIJU' {
                memory = '100.GB'
                cpus   = '18'
        }
        withName: 'GANON_CLASSIFY' {
                memory = '72.GB'
                cpus   = '18'
        }
	withName: 'KMCP_PROFILE' {
		memory = '240.GB'
		cpus = '72'
		time = '24.h'
	}
        withName: 'KRAKEN2_KRAKEN2'{
                memory = '240.GB'
                cpus   = '72'
        }
        withName: 'BRACKEN_BRACKEN'{
                memory = '240.GB'
                cpus   = '72'
        }
        withName: 'METACACHE_QUERY' {
                memory = '240.GB'
                cpus = '72'
        }
        withName: 'KRAKENUNIQ_PRELOADEDKRAKENUNIQ' {
                memory = '2047.GB'
                cpus = '72'
                time = '24.h'
        }
        withName: 'CENTRIFUGE_CENTRIFUGE' {
                maxForks = 1
		memory = '72.GB'
                cpus = '18'
                time = '24.h'
        }
	withName: 'TAXPASTA_MERGE' {
		errorStrategy = 'ignore'
		memory = '24.GB'
		cpus = '1'
		time = '4.h'
	}
}
```

For small database runs `custom_small.config`

```{groovy}
process {
	withName: 'FASTP_PAIRED' {
		cpus   = 24
		memory = '90.GB'
	}
        withName: 'PORECHOP_ABI' {
                cpus = 24
                memory = '110.GB'
        }
        withName: 'NANOQ' {
                cpus = 24
                memory = '110.GB'
        }
	withName: 'SAMTOOLS_STATS' {
		memory = '32.GB'
	}
	withName: 'NONPAREIL_NONPAREIL' {
		ext.args = "-k 15"
	} 
        withName: 'KAIJU_KAIJU' {
                memory = '50.GB'
                cpus   = '30'
        }
        withName: 'GANON_CLASSIFY' {
                memory = '15.GB'
                cpus   = '30'
        }
	withName: 'DIAMOND_BLASTX' {
		memory = '50.GB'
		cpus = '30'
	}
	withName: 'KMCP_PROFILE' {
		memory = '50.GB'
		cpus = '30'
		time = '24.h'
	}
	withName: 'KMCP_SEARCH' {
		memory = '50.GB'
		cpus = '30'
	}
        withName: 'KRAKEN2_KRAKEN2'{
                memory = '50.GB'
                cpus   = '30'
        }
        withName: 'BRACKEN_BRACKEN'{
                memory = '10.GB'
                cpus   = '30'
        }
        withName: 'METACACHE_QUERY' {
                memory = '100.GB'
                cpus = '30'
        }
        withName: 'KRAKENUNIQ_PRELOADEDKRAKENUNIQ' {
                memory = '500.GB'
                cpus = '72'
                time = '24.h'
        }
        withName: 'CENTRIFUGE_CENTRIFUGE' {
                maxForks = 1
		memory = '20.GB'
                cpus = '30'
                time = '24.h'
        }
	withName: 'TAXPASTA_MERGE' {
		errorStrategy = 'ignore'
		memory = '24.GB'
		cpus = '1'
		time = '4.h'
	}
	withName: 'MOTUS_PROFILES' {
		memory = '50.GB'
		cpus = 30
	}
	withName: 'SYLPH_PROFILE'{
		memory = '30.GB'
		cpus = 30
	}
	withName: 'MELON' {
		memory = '64.GB'
		cpus = 30
	}
	withName: 'MOTUS_PREPLONG' {
		memory = '8.GB'
		cpus = 8
		time = '16.h'
	}
	
}
```

For small ONT runs:

```{groovy}
process {
	withName: 'FASTP_PAIRED' {
		cpus   = 24
		memory = '90.GB'
	}
        withName: 'PORECHOP_ABI' {
                cpus = 24
                memory = '110.GB'
        }
        withName: 'NANOQ' {
                cpus = 24
                memory = '110.GB'
        }
	withName: 'SAMTOOLS_STATS' {
		memory = '32.GB'
	}
	withName: 'NONPAREIL_NONPAREIL' {
		ext.args = "-k 15"
	} 
        withName: 'KAIJU_KAIJU' {
                memory = '50.GB'
                cpus   = '30'
        }
        withName: 'GANON_CLASSIFY' {
                memory = '15.GB'
                cpus   = '30'
        }
	withName: 'DIAMOND_BLASTX' {
		memory = '50.GB'
		cpus = '30'
	}
	withName: 'KMCP_PROFILE' {
		memory = '50.GB'
		cpus = '30'
		time = '24.h'
	}
	withName: 'KMCP_SEARCH' {
		memory = '50.GB'
		cpus = '30'
	}
        withName: 'KRAKEN2_KRAKEN2'{
                memory = '100.GB'
                cpus   = '30'
        }
        withName: 'BRACKEN_BRACKEN'{
                memory = '10.GB'
                cpus   = '30'
        }
        withName: 'METACACHE_QUERY' {
                memory = '100.GB'
                cpus = '30'
        }
        withName: 'KRAKENUNIQ_PRELOADEDKRAKENUNIQ' {
                memory = '500.GB'
                cpus = '72'
                time = '24.h'
        }
        withName: 'CENTRIFUGE_CENTRIFUGE' {
		memory = '100.GB'
                cpus = '30'
                time = '24.h'
        }
	withName: 'TAXPASTA_MERGE' {
		errorStrategy = 'ignore'
		memory = '24.GB'
		cpus = '1'
		time = '4.h'
	}
	withName: 'MOTUS_PROFILES' {
		memory = '50.GB'
		cpus = 30
	}
	withName: 'SYLPH_PROFILE'{
		memory = '30.GB'
		cpus = 30
	}
	withName: 'MELON' {
		memory = '64.GB'
		cpus = 30
	}
	withName: 'MOTUS_PREPLONG' {
		memory = '8.GB'
		cpus = 8
		time = '16.h'
	}
	
}
```

#### deNBI cloud

For `custom.config`:

```{groovy}
process {
        withName: 'FASTP_PAIRED' {
                cpus   = 20
                memory = '100.GB'
        }
        withName: 'NONPAREIL_NONPAREIL' {
                ext.args = "-k 15"
        } 
        withName: 'KAIJU_KAIJU' {
                memory = '100.GB'
                cpus   = '20'
        }
        withName: 'GANON_CLASSIFY' {
                memory = '100.GB'
                cpus   = '20'
        }
        withName: 'KMCP_PROFILE' {
                memory = '400.GB'
                cpus = '20'
                time = '365.d'
        }
        withName: 'KRAKEN2_KRAKEN2'{
                memory = '100.GB'
                cpus   = '20'
        }
        withName: 'BRACKEN_BRACKEN'{
                memory = '120.GB'
                cpus   = '20'
        }
        withName: 'METACACHE_QUERY' {
                memory = '100.GB'
                cpus = '20'
        }
        withName: 'KRAKENUNIQ_PRELOADEDKRAKENUNIQ' {
                memory = '900.GB'
                cpus = '56'
        }
        withName: 'CENTRIFUGE_CENTRIFUGE' {
                memory = '400.GB'
                cpus = '20'
                time = '365.d'
        }
        withName: 'TAXPASTA_MERGE' {
                errorStrategy = 'ignore'
                memory = '24.GB'
                cpus = '1'
        }
        withName: 'KRAKEN2_KRAKEN2' {
                memory = '144.GB'
                cpus = 24
        }
}
```

For `custom_small_ont.config`:

```{groovy}
process {
        withName: 'FASTQC' {
                memory = '8.GB'
                cpus = 5
                time = '24.d'
        }
        withName: 'PORECHOP_ABI' {
                memory = '120.GB'
                cpus = 12
                time = '24.d'
        }
        withName: 'NANOQ' {
                memory = '4.GB'
                cpus = 4
                time = '24.d'
        }
        withName: 'MINIMAP2_ALIGN' {
                memory = '28.GB'
                cpus = 12
                time = '24.d'
        }
        withName: 'SAMTOOLS_STATS' {
                memory = '12.GB'
                cpus = 4
                time = '24.d'
        }
        withName: 'FASTQC_PROCESSED' {
                memory = '24.GB'
                cpus = 7
                time = '24.d'
        }
        withName: 'SAMTOOLS_VIEW' {
                memory = '4.GB'
                cpus = 4
                time = '24.d'
        }
        withName: 'SAMTOOLS_FASTQ' {
                memory = '4.GB'
                cpus = 4
                time = '24.d'
        }
        withName: 'METACACHE_QUERY' {
                memory = '100.GB'
                cpus = 12
                time = '24.d'
        }
        withName: 'SYLPH_PROFILE' {
                memory = '16.GB'
                cpus = 7
                time = '24.d'
        }
        withName: 'SYLPHTAX_TAXPROF' {
                memory = '4.GB'
                cpus = 4
                time = '24.d'
        }
        withName: 'KAIJU_KAIJU' {
                memory = '64.GB'
                cpus = 28
                time = '24.d'
        }
        withName: 'KAIJU_KAIJU2TABLE_SINGLE' {
                memory = '4.GB'
                cpus = 4
                time = '24.d'
        }
        withName: 'KAIJU_KREPORT2KRONA' {
                memory = '4.GB'
                cpus = 4
                time = '24.d'
        }
        withName: 'CENTRIFUGE_CENTRIFUGE' {
                memory = '48.GB'
                cpus = 12
                time = '24.d'
        }
        withName: 'CENTRIFUGE_KREPORT' {
                memory = '4.GB'
                cpus = 4
                time = '24.d'
        }
        withName: 'MELON' {
                memory = '32.GB'
                cpus = 14
                time = '24.d'
        }
        withName: 'MOTUS_PREPLONG' {
                memory = '4.GB'
                cpus = 4
                time = '24.d'
        }
        withName: 'MOTUS_PROFILE' {
                memory = '32.GB'
                cpus = 14
                time = '24.d'
        }
        withName: 'DIAMOND_BLASTX' {
                memory = '32.GB'
                cpus = 14
                time = '24.d'
        }
        withName: 'KRAKENUNIQ_PRELOADEDKRAKENUNIQ' {
                memory = '900.GB'
                cpus = 56
                time = '24.d'
        }
        withName: 'KAIJU_KAIJU2TABLE_COMBINED' {
                memory = '4.GB'
                cpus = 4
                time = '24.d'
        }
        withName: 'TAXPASTA_MERGE' {
                memory = '7.GB'
        }
}
```

## Execution (Ancient DNA Illumina)

We can then run nf-core/taxprofiler on this dataset of 3 differently depth-sequenced sequencing runs with the databases we generated previously.

### 30k

(Note: we had to run on different infrastructure due to wall-time restrictions, compared to the smaller database runs).

For example, for the full dataset of just under ~30,000 genomes:

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /vol/permanent/benchmarking/samplesheets/taxprofiler-samplesheet_denbi.csv \
 --databases /vol/permanent/benchmarking/samplesheets/taxprofiler-databases_denbi30000.csv \
 -name txp_benchmark_30000 \
 --outdir /vol/permanent/benchmarking/taxprofiler/results_illumina_30000/ \
 --perform_shortread_qc \
 --shortread_qc_dedup \
 --perform_shortread_complexityfilter \
 --perform_shortread_redundancyestimation \
 --perform_shortread_hostremoval \
 --hostremoval_reference /vol/permanent/benchmarking/reference/human-t2t-hla.fa.gz \
 --shortread_hostremoval_index /vol/permanent/benchmarking/reference/ \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_metaphlan \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /vol/permanent/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /vol/permanent/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom.config
```


### 20k

Note: we had to run on different infrastructure due to walltime restrictions.

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /vol/permanent/benchmarking/samplesheets/taxprofiler-samplesheet_denbi.csv \
 --databases /vol/permanent/benchmarking/samplesheets/taxprofiler-databases_denbi20000.csv \
 -name txp_benchmark_20000 \
 --outdir /vol/permanent/benchmarking/taxprofiler/results_illumina_20000/ \
 --perform_shortread_qc \
 --shortread_qc_dedup \
 --perform_shortread_complexityfilter \
 --perform_shortread_redundancyestimation \
 --perform_shortread_hostremoval \
 --hostremoval_reference /vol/permanent/benchmarking/reference/human-t2t-hla.fa.gz \
 --shortread_hostremoval_index /vol/permanent/benchmarking/reference/ \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_metaphlan \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /vol/permanent/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /vol/permanent/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom.config
```

### 10k

Note: we had to run on different infrastructure due to walltime restrictions.

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /vol/permanent/benchmarking/samplesheets/taxprofiler-samplesheet_denbi.csv \
 --databases /vol/permanent/benchmarking/samplesheets/taxprofiler-databases_denbi10000.csv \
 -name txp_benchmark_10000 \
 --outdir /vol/permanent/benchmarking/taxprofiler/results_illumina_10000/ \
 --perform_shortread_qc \
 --shortread_qc_dedup \
 --perform_shortread_complexityfilter \
 --perform_shortread_redundancyestimation \
 --perform_shortread_hostremoval \
 --hostremoval_reference /vol/permanent/benchmarking/reference/human-t2t-hla.fa.gz \
 --shortread_hostremoval_index /vol/permanent/benchmarking/reference/ \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_metaphlan \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /vol/permanent/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /vol/permanent/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom.config
```

### 5k

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-samplesheet_raven.csv \
 --databases /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-databases_raven5000.csv \
 -profile mpcdf,raven \
 -name txp_benchmark_5000 \
 --outdir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/results_illumina_5000/ \
 --perform_shortread_qc \
 --shortread_qc_dedup \
 --perform_shortread_complexityfilter \
 --perform_shortread_redundancyestimation \
 --perform_shortread_hostremoval \
 --hostremoval_reference /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.fa.gz \
 --shortread_hostremoval_index /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/ \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_metaphlan \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom_small.config
```

### 2k

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-samplesheet_raven.csv \
 --databases /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-databases_raven2000.csv \
 -profile mpcdf,raven \
 -name txp_benchmark_2000 \
 --outdir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/results_illumina_2000/ \
 --perform_shortread_qc \
 --shortread_qc_dedup \
 --perform_shortread_complexityfilter \
 --perform_shortread_redundancyestimation \
 --perform_shortread_hostremoval \
 --hostremoval_reference /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.fa.gz \
 --shortread_hostremoval_index /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/ \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_metaphlan \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom_small.config
```

### 1k

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-samplesheet_raven.csv \
 --databases /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-databases_raven1000.csv \
 -profile mpcdf,raven \
 -name txp_benchmark_1000 \
 --outdir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/results_illumina_1000/ \
 --perform_shortread_qc \
 --shortread_qc_dedup \
 --perform_shortread_complexityfilter \
 --perform_shortread_redundancyestimation \
 --perform_shortread_hostremoval \
 --hostremoval_reference /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.fa.gz \
 --shortread_hostremoval_index /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/ \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_metaphlan \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom_small.config
```

### Aggregation

To get all the hard drive usage statistics (although not used for final plotting).

```{bash}
#| eval: false
## WHILE IN `taxprofiler/`
mkdir -p ../resource_tracking/taxprofiler_illumina/
for i in results_illumina_*; do du --max-depth 1 $i >> ../resource_tracking/taxprofiler_illumina/taxprofiler_illumina_resource_usage_raw.tsv; done
for i in results_illumina_*; do du -h --max-depth 1 $i >> ../resource_tracking/taxprofiler_illumina/taxprofiler_illumina_resource_usage_humanreadable.tsv; done
```

And to get all trace files.

```{bash}
for i in results_illumina_*; do
  mkdir ../resource_tracking/taxprofiler_illumina/"$i"/
  cp -r "$i"/pipeline_info/ ../resource_tracking/taxprofiler_illumina/"$i"/pipeline_info/
done
```

## Execution (Nanopore dataset)

We did not run MetaPhlan due to a [known problem](https://forum.biobakery.org/t/metaphlan-4-x-support-for-long-reads/7948) with <= v4.1 (the version in nf-core/taxprofiler) and long read data, where Bowtie2 would require too much memory.

### 30k

Note: had to run this on other infrastructure due to walltime limitations.

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /vol/permanent/benchmarking/samplesheets/taxprofiler-samplesheet_ont_denbi.csv \
 --databases /vol/permanent/benchmarking/samplesheets/taxprofiler-databases_denbi30000.csv \
 -name txp_benchmark_ont_30000 \
 --outdir /vol/permanent/benchmarking/taxprofilerresults_ont_30000/ \
 --perform_longread_qc \
 --perform_longread_hostremoval \
 --hostremoval_reference /vol/permanent/benchmarking/reference/human-t2t-hla.fa.gz \
 --longread_hostremoval_index /vol/permanent/benchmarking/reference/human-t2t-hla.mmi \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /vol/permanent/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /vol/permanent/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom_small_ont.config
```

### 20k

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-samplesheet_ont_raven.csv \
 --databases /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-databases_raven20000.csv \
 -profile mpcdf,raven \
 -name txp_benchmark_ont_20000 \
 --outdir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/results_ont_20000/ \
 --perform_longread_qc \
 --perform_longread_hostremoval \
 --hostremoval_reference /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.fa.gz \
 --longread_hostremoval_index /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.mmi \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom_small_ont.config
```

### 10k

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-samplesheet_ont_raven.csv \
 --databases /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-databases_raven10000.csv \
 -profile mpcdf,raven \
 -name txp_benchmark_ont_10000 \
 --outdir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/results_ont_10000/ \
 --perform_longread_qc \
 --perform_longread_hostremoval \
 --hostremoval_reference /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.fa.gz \
 --longread_hostremoval_index /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.mmi \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom_small.config
```

### 5k

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-samplesheet_ont_raven.csv \
 --databases /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-databases_raven5000.csv \
 -profile mpcdf,raven \
 -name txp_benchmark_ont_5000 \
 --outdir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/results_ont_5000/ \
 --perform_longread_qc \
 --perform_longread_hostremoval \
 --hostremoval_reference /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.fa.gz \
 --longread_hostremoval_index /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.mmi \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom_small.config
```

### 2k

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-samplesheet_ont_raven.csv \
 --databases /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-databases_raven2000.csv \
 -profile mpcdf,raven \
 -name txp_benchmark_ont_2000 \
 --outdir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/results_ont_2000/ \
 --perform_longread_qc \
 --perform_longread_hostremoval \
 --hostremoval_reference /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.fa.gz \
 --longread_hostremoval_index /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.mmi \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom_small.config
```

### 1k

```{bash}
#| eval: false
nextflow run nf-core/taxprofiler \
 -r 2.0.0 \
 --input /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-samplesheet_ont_raven.csv \
 --databases /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/samplesheets/taxprofiler-databases_raven1000.csv \
 -profile mpcdf,raven \
 -name txp_benchmark_ont_1000 \
 --outdir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/results_ont_1000/ \
 --perform_longread_qc \
 --perform_longread_hostremoval \
 --hostremoval_reference /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.fa.gz \
 --longread_hostremoval_index /raven/ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/taxprofiler/reference/human-t2t-hla.mmi \
 --run_bracken \
 --run_centrifuge \
 --run_diamond \
 --run_ganon \
 --run_kaiju \
 --run_kmcp \
 --run_kraken2 \
 --run_krakenuniq \
 --run_melon \
 --run_metacache \
 --run_motus \
 --run_sylph \
 --run_profile_standardisation \
 --run_krona \
 --taxpasta_taxonomy_dir /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/ \
 --sylph_taxonomy /ptmp/jfellowsy/projects/taxprofiler-createtaxdb-paper/benchmarking/auxiliary_files/sylph_taxonomy.tsv \
 -c custom_small.config
```


### Aggregation

To aggregate all the results directory `du` commands all into one file (even if not used for plotting in the end), we can use the following:

```{bash}
#| eval: false
## Reminder, must be in `taxprofiler/`
mkdir -p ../resource_tracking/taxprofiler_ont/
for i in results_ont_*; do du --max-depth 1 $i >> ../resource_tracking/taxprofiler_ont/taxprofiler_ont_resource_usage_raw.tsv; done
for i in results_ont_*; do du -h --max-depth 1 $i >> ../resource_tracking/taxprofiler_ont/taxprofiler_ont_resource_usage_humanreadable.tsv; done
```

And to get all trace files

```{bash}
#| eval: false
## Reminder, must be in `taxprofiler/`
for i in results_ont_*; do
  mkdir ../resource_tracking/taxprofiler_ont/"$i"/
  cp -r "$i"/pipeline_info/ ../resource_tracking/taxprofiler_ont/"$i"/pipeline_info/
done
```
